// AUTO-GENERATED BY GitHub Actions — Sync Mercado Público 2026-07-29
// DO NOT EDIT MANUALLY — Se sobreescribe automáticamente cada 3 horas
import { Oportunidad, Postulacion, MiembroEquipo, VistaGuardada, Notificacion, OrdenCompra } from './types';

export const mockOportunidades: Oportunidad[] = [];

export const mockPostulaciones: Postulacion[] = [
  {
    "id": "post-b1",
    "oportunidadId": "op-1001-11-COT26",
    "oportunidadCodigo": "1001-11-COT26",
    "oportunidadTitulo": "Retiro, traslado e instalación de equipos de aire acondicionado",
    "organismo": "MINISTERIO DE SALUD - SERVICIO DE SALUD METROPOLITANO",
    "empresaMatch": "Aminorte",
    "modalidad": "Compra Ágil",
    "responsable": "Jonathan Cooper",
    "montoOferta": 2450000,
    "fechaActualizacion": "2026-07-29",
    "estado": "Borrador",
    "documentosAdjuntos": [
      "Cotizacion_AireAcondicionado_Aminorte.pdf"
    ],
    "itemsOfertados": [
      {
        "sku": "SKU-HVAC-01",
        "precioOferta": 2450000,
        "cantidad": 1
      }
    ]
  }
];

export const mockMiembrosEquipo: MiembroEquipo[] = [
  { id: 'usr-1', nombre: 'Jonathan Cooper', rol: 'Admin', avatar: 'JC', estado: 'Activo', email: 'jcooper@inder-roll.cl' },
  { id: 'usr-2', nombre: 'Manuel Viguera', rol: 'Gestor', avatar: 'MV', estado: 'Activo', email: 'mviguera@aminorte.cl' },
  { id: 'usr-3', nombre: 'Jorge Alvarado', rol: 'Gestor', avatar: 'JA', estado: 'Activo', email: 'jorge.alvarado@discoverymerch.cl' },
  { id: 'usr-4', nombre: 'José San Martín', rol: 'Gestor', avatar: 'JS', estado: 'Activo', email: 'jsanmartin@aminorte.cl' }
];

export const mockNotificaciones: Notificacion[] = [
  { id: 'n-1', titulo: 'Sync Automático Activo', descripcion: 'Última sincronización: 2026-07-29 — 0 procesos desde API Mercado Público.', fecha: '2026-07-29', leida: false, tipo: 'info' }
];

export const mockVistasGuardadas: VistaGuardada[] = [
  { id: 'v-1', nombre: 'Compras Ágiles Vigentes', filters: { search: '', rubro: 'Todos', region: 'Todos', riesgo: 'Todos', montoMin: 0, montoMax: 4000000 } }
];

export const mockOrdenesCompra: OrdenCompra[] = [
  { id: 'oc-1', oportunidadId: 'op-ca-5', codigoOC: 'OC-1005-26', organismo: 'HOSPITAL REGIONAL DR. JUAN NOÉ ARICA', monto: 3450000, fechaEmision: '2026-07-24', estado: 'Aceptada' }
];

export const FLETES_REGIONALES_CHILE: Record<string, { fleteBase: number; diasEntrega: string; zona: string }> = {
  'Región Metropolitana': { fleteBase: 0, diasEntrega: '24 hrs', zona: 'Zona Central (RM)' },
  'Región de Valparaíso': { fleteBase: 15000, diasEntrega: '24-48 hrs', zona: 'Zona Centro' },
  'Región de Coquimbo': { fleteBase: 25000, diasEntrega: '48 hrs', zona: 'Zona Norte Chico' },
  'Región del Libertador General Bernardo O\'Higgins': { fleteBase: 18000, diasEntrega: '24-48 hrs', zona: 'Zona Centro-Sur' },
  'Región del Maule': { fleteBase: 22000, diasEntrega: '48 hrs', zona: 'Zona Centro-Sur' },
  'Región de Ñuble': { fleteBase: 28000, diasEntrega: '48 hrs', zona: 'Zona Sur' },
  'Región del Biobío': { fleteBase: 32000, diasEntrega: '48-72 hrs', zona: 'Zona Sur' },
  'Región de La Araucanía': { fleteBase: 38000, diasEntrega: '72 hrs', zona: 'Zona Sur' },
  'Región de Los Ríos': { fleteBase: 42000, diasEntrega: '72 hrs', zona: 'Zona Sur' },
  'Región de Los Lagos': { fleteBase: 48000, diasEntrega: '72-96 hrs', zona: 'Zona Sur-Austral' },
  'Región de Aysén del General Carlos Ibáñez del Campo': { fleteBase: 85000, diasEntrega: '5-7 días', zona: 'Zona Austral' },
  'Región de Magallanes y de la Antártica Chilena': { fleteBase: 95000, diasEntrega: '5-7 días', zona: 'Zona Austral' },
  'Región de Atacama': { fleteBase: 45000, diasEntrega: '48-72 hrs', zona: 'Zona Norte' },
  'Región de Antofagasta': { fleteBase: 55000, diasEntrega: '72 hrs', zona: 'Zona Norte Grande' },
  'Región de Tarapacá': { fleteBase: 65000, diasEntrega: '72-96 hrs', zona: 'Zona Norte Grande' },
  'Región de Arica y Parinacota': { fleteBase: 75000, diasEntrega: '4-5 días', zona: 'Zona Norte Extrema' }
};
